package biz.noorlander.batclient.ui;

import javax.swing.*;
import java.awt.*;

public class AnimistSoulFrame {
    private JLabel pointsAvailable;
    private JLabel mountLevel;
    private JLabel mountProgress;
    private JPanel animistSoulPanel;

    public JPanel getAnimistSoulPanel() {
        return animistSoulPanel;
    }

    public void setMountLevel(String mountLevel) {
        this.mountLevel.setText(mountLevel);
    }

    public void setMountProgress(String mountProgress) {
        this.mountProgress.setText(mountProgress);
    }

    public void setPointsAvailable(int pointsAvailable) {
        this.pointsAvailable.setText(String.valueOf(pointsAvailable));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        animistSoulPanel = new JPanel();
        animistSoulPanel.setLayout(new GridBagLayout());
        animistSoulPanel.setBackground(new Color(-14540254));
        animistSoulPanel.setForeground(new Color(-12171706));
        animistSoulPanel.setPreferredSize(new Dimension(240, 48));
        final JLabel label1 = new JLabel();
        label1.setText("Points available");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        animistSoulPanel.add(label1, gbc);
        pointsAvailable = new JLabel();
        pointsAvailable.setForeground(new Color(-10578245));
        pointsAvailable.setHorizontalAlignment(10);
        pointsAvailable.setText("1234");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        animistSoulPanel.add(pointsAvailable, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Mount level");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        animistSoulPanel.add(label2, gbc);
        mountLevel = new JLabel();
        mountLevel.setForeground(new Color(-10578245));
        mountLevel.setText("Chicken");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        animistSoulPanel.add(mountLevel, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Mount progress");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        animistSoulPanel.add(label3, gbc);
        mountProgress = new JLabel();
        mountProgress.setForeground(new Color(-10578245));
        mountProgress.setText("0%");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        animistSoulPanel.add(mountProgress, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return animistSoulPanel;
    }

}
